trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: htune_ROC_AUC
    maxTrials: 2
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:
    - parameterName: class_weight_ratio
      type: DOUBLE
      minValue: 1.0
      maxValue: 4.0
    - parameterName: initial_lr
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.01
    - parameterName: lr_decay_param
      type: INTEGER
      minValue: 10
      maxValue: 100
    - parameterName: batch_size
      type: DISCRETE
      discreteValues:
      - 32
      - 64
    - parameterName: hidden_depth
      type: DISCRETE
      discreteValues:
      - 1
      - 2
      - 3
    - parameterName: hidden_nodes
      type: DISCRETE
      discreteValues:
      - 16
      - 32
      - 64
    - parameterName: hidden_activation
      type: CATEGORICAL
      categoricalValues:
      - elu
      - selu
    - parameterName: optimizer
      type: CATEGORICAL
      categoricalValues:
      - Adam
      - RMSprop
